### ISSUE TITLE
제안서 리뷰

### ISSUE THREAD

**Issue by MisooKim2** [jeongchan20/CPP202309-P#1]
1. 구현할 기능들이 다소 단순해 보입니다. 무지출 날짜가 나오는 차별점은 좋으나, 제약 조건이나 세부 기능이 추가되면 좋을 것 같습니다. (예: 사용자에게 특정 카테고리를 입력받고, 해당 카테고리를 제외한 것들에서의 무지출 여부. 예를 들면 밥은 먹어야 하니까... 식비는 제외하고 무지출이 얼마나 이루어졌는지 등)
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by jeongchan20** [comment]
완료
